# Generated by Django 6.0.2 on 2026-02-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='tags',
            new_name='tag',
        ),
    ]
